#ifndef EVENT_H
#define EVENT_H

enum ENUM_EVENT
{
	EVENT_NONE = 0,
	EVENT_MOUSEMOVE,
	EVENT_LMOUSECLICK,
	EVENT_LMOUSERELEASED,
	EVENT_RMOUSECLICK,
	EVENT_MOUSEENTERED,
	EVENT_MOUSEEXITED
};

#endif // EVENT_H